---
- hosts: all
  become: yes
  gather_facts: yes

  roles:
    - geerlingguy.nfs
    - geerlingguy.packer-debian

  tasks:
  - name: install essential dependencies
    apt: 
      pkg: "{{ item }}"
      state: present
      update_cache: yes
    with_items:
      - git
      - wget
      - curl
      - python-pip
      - unzip
      - tree
      - gnupg2
      - gnupg-agent
      - apt-transport-https
      - ca-certificates
      - software-properties-common
      - jq
      - python-dev
      - python-pip
      - python3-dev
      - python3-pip
      - bats
      - bc
      - whois
      - tmux

  - name: Install awscli
    pip:
      name: awscli

  - name: Install Neovim Repo
    apt_repository:
      repo: ppa:neovim-ppa/stable
      state: present

  - name: Install neovim
    apt:
      name: neovim
      state: present

  - name: Update alternatives
    become: yes
    alternatives:
      name: "{{ item }}"
      path: /usr/bin/nvim
    with_items:
      - ex
      - rview
      - rvim
      - vi
      - view
      - vim
      - vimdiff

  - name: Install Docker GPG Key
    apt_key:
      id: 0EBFCD88
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present

  - name: Install Docker Repo
    apt_repository:
      repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable 
      state: present

  - name: Install Docker
    apt:
      name: docker-ce
      state: present

  - name: Install go1.11
    unarchive:
      src: https://dl.google.com/go/go1.11.linux-amd64.tar.gz
      dest: /usr/local
      remote_src: True

  - name: Add Go exec path
    lineinfile:
      path: /etc/profile
      line: 'export PATH=$PATH:/usr/local/go/bin'

  - name: Install diff-so-fancy
    get_url:
      url: https://raw.githubusercontent.com/so-fancy/diff-so-fancy/master/third_party/build_fatpack/diff-so-fancy
      dest: /usr/local/bin/diff-so-fancy
      mode: 0755

  - name: Install Terraform
    unarchive:
      src: https://releases.hashicorp.com/terraform/0.11.8/terraform_0.11.8_linux_amd64.zip
      dest: /usr/local/bin
      remote_src: True
      mode: 0755

  - name: Download Terragrunt
    get_url:
      url: https://github.com/gruntwork-io/terragrunt/releases/download/v0.16.7/terragrunt_linux_amd64
      dest: /usr/local/bin/terragrunt
      mode: 0755

  - name: Install Chef
    apt:
      deb: https://packages.chef.io/files/stable/chefdk/3.3.23/ubuntu/18.04/chefdk_3.3.23-1_amd64.deb

  - name: Install Packer
    unarchive:
      src: https://releases.hashicorp.com/packer/1.3.1/packer_1.3.1_linux_amd64.zip
      dest: /usr/local/bin
      remote_src: True
      mode: 0755
